apiVersion: apps/v1
kind: Deployment
metadata:
  name:  node-app
  labels:
    name:  node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-app
  template:
    metadata:
      labels:
        name: node-app
    spec:
      containers:
      - image: 4141817/kube_node_app:4ceb3da41f2e3d5d30557e510d85ca24e74f8244
        name: node-app-container    
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "64Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: regcred   