apiVersion: apps/v1
kind: Deployment
metadata:
  name:  node-app
  labels:
    name:  node-app
spec:
  selector:
    matchLabels:
      name: node-app
  template:
    metadata:
      labels:
        name: node-app
    spec:
      containers:
      - image: 4141817/kube_node_app:2b5467437ca8e13106ac5426ac39c0a0bf2115ae
        name: node-app-container    
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "150m"
          limits:
            memory: "64Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: regcred   