apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: node-app
  name: node-app-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: node-app
  type: ClusterIP
status:
  loadBalancer: {}  